#!/bin/sh
xrandr --output VGA-1 --off --output LVDS-1 --primary --mode 1366x768 --pos 0x312 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --mode 2560x1080 --pos 1366x0 --rotate normal --output DP-1 --off
